Upgrade courier-imap (#11)
* Upgrade courier-imap

upgrade courier-imap and libs

1. upgrade courier-imap to 5.1.1
2. upgrade unicode to 2.2.2
3. upgrade maildrop to 3.0.3

* upgrade courier-imap

* updated workflow to get triggered on PRs

* added missing Makefile

diff --git a/courier-imap-x/imapd-ssl.rc.in b/courier-imap-x/imapd-ssl.rc.in
--- a/courier-imap-x/imapd-ssl.rc.in
+++ b/courier-imap-x/imapd-ssl.rc.in
@@ -36,32 +36,40 @@ start)
 		chmod 600  "$TLS_CACHEFILE"
 	fi
 
-	umask $IMAP_UMASK
+	umask ${IMAP_UMASK:=022}
 	if test ! -f "${IMAPACCESSFILE}.dat"
 	then
-		@bindir@/makeimapaccess
+		if test -e "${IMAPACCESSFILE}"
+		then
+			@bindir@/makeimapaccess
+		else
+			echo "IMAPACCESSFILE is missing." >&2
+			exit 1
+		fi
+	fi
+	if test ! -z "$IMAP_ULIMITD"
+	then
+		@ULIMIT@ $IMAP_ULIMITD
 	fi
 
-	@ULIMIT@ $IMAP_ULIMITD
-	@SETENV@ -i @SHELL@ -c " set -a ;
-		prefix=@prefix@ ;
-		exec_prefix=@exec_prefix@ ;
-		bindir=@bindir@ ;
-		libexecdir=@libexecdir@ ;
-		. @sysconfdir@/imapd ; \
-		. @sysconfdir@/imapd-ssl ; \
-		PROXY_HOSTNAME=$PROXY_HOSTNAME ; \
-		IMAP_TLS=1; \
-		@MKDIR_P@ `dirname $SSLPIDFILE` ; \
-		@courierlogger@ -pid=$SSLPIDFILE -start $SSLLOGGEROPTS \
-		@libexecdir@/couriertcpd -address=$SSLADDRESS \
-			-maxprocs=$MAXDAEMONS -maxperip=$MAXPERIP \
-			-access=$IMAPACCESSFILE.dat \
-			$TCPDOPTS \
-			$SSLPORT $COURIERTLS -server -tcpd \
-				-user=@authmailuser@ \
-				@sbindir@/imaplogin \
-				@bindir@/imapd ${MAILDIRPATH}"
+	prefix=@prefix@ ;
+	exec_prefix=@exec_prefix@ ;
+	bindir=@bindir@ ;
+	libexecdir=@libexecdir@ ;
+	. @sysconfdir@/imapd ; \
+	. @sysconfdir@/imapd-ssl ; \
+	PROXY_HOSTNAME=$PROXY_HOSTNAME ; \
+	IMAP_TLS=1; \
+	@MKDIR_P@ `dirname $SSLPIDFILE` ; \
+	@courierlogger@ -pid=$SSLPIDFILE -start $SSLLOGGEROPTS \
+	@libexecdir@/couriertcpd -address=$SSLADDRESS \
+		-maxprocs=$MAXDAEMONS -maxperip=$MAXPERIP \
+		-access=$IMAPACCESSFILE.dat \
+		$TCPDOPTS \
+		$SSLPORT $COURIERTLS -server -tcpd \
+			-user=@authmailuser@ \
+			@sbindir@/imaplogin \
+			@bindir@/imapd ${MAILDIRPATH}"
 	;;
 stop)
 	@courierlogger@ -pid=$SSLPIDFILE -stop
diff --git a/courier-imap-x/imapd.rc.in b/courier-imap-x/imapd.rc.in
--- a/courier-imap-x/imapd.rc.in
+++ b/courier-imap-x/imapd.rc.in
@@ -36,19 +36,28 @@ start)
 		chmod 600  "$TLS_CACHEFILE"
 	fi
 
+	umask ${IMAP_UMASK:=022}
 	if test ! -f "${IMAPACCESSFILE}.dat"
 	then
-		@bindir@/makeimapaccess
+		if test -e "${IMAPACCESSFILE}"
+		then
+			@bindir@/makeimapaccess
+		else
+			echo "IMAPACCESSFILE is missing." >&2
+			exit 1
+		fi
 	fi
-	umask $IMAP_UMASK
-	@ULIMIT@ $IMAP_ULIMITD
+	if test ! -z "$IMAP_ULIMITD"
+	then
+		@ULIMIT@ $IMAP_ULIMITD
+	fi
 	@SETENV@ -i @SHELL@ -c " set -a ;
-			prefix=@prefix@ ;
-			exec_prefix=@exec_prefix@ ;
-			bindir=@bindir@ ;
-			libexecdir=@libexecdir@ ;
-				. @sysconfdir@/imapd-ssl ; \
-				. @sysconfdir@/imapd ; \
+		prefix=@prefix@ ;
+		exec_prefix=@exec_prefix@ ;
+		bindir=@bindir@ ;
+		libexecdir=@libexecdir@ ;
+			. @sysconfdir@/imapd-ssl ; \
+			. @sysconfdir@/imapd ; \
 		IMAP_STARTTLS=$IMAPDSTARTTLS ; \
 		PROXY_HOSTNAME=$PROXY_HOSTNAME ; \
 		TLS_PROTOCOL=$TLS_STARTTLS_PROTOCOL ; \
@@ -58,7 +67,7 @@ start)
 			-maxprocs=$MAXDAEMONS -maxperip=$MAXPERIP \
 			-access=$IMAPACCESSFILE.dat \
 			$TCPDOPTS \
-			$PORT @sbindir@/imaplogin @bindir@/imapd ${MAILDIRPATH}"
+		$PORT @sbindir@/imaplogin @bindir@/imapd ${MAILDIRPATH}"
 	;;
 stop)
 	@courierlogger@ -pid=$PIDFILE -stop
