fixed ismaildup, makeseekable logic
1. Refactored ismaildup
2. Fix delivery without MAKE_SEEKABLE set

diff --git a/indimail-x/tests/testindimail-virtual b/indimail-x/tests/testindimail-virtual
--- a/indimail-x/tests/testindimail-virtual
+++ b/indimail-x/tests/testindimail-virtual
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: testindimail-virtual,v 1.16 2023-10-22 22:37:00+05:30 Cprogrammer Exp mbhangui $
+# $Id: testindimail-virtual,v 1.17 2023-10-23 18:47:37+05:30 Cprogrammer Exp mbhangui $
 #
 start=$(date +'%s')
 user=$(whoami)
@@ -1201,7 +1201,13 @@ do_smtp_auth_swaks()
 				else
 					fcount=$(expr $fcount + 1)
 					if [ $prompt -eq 1 ] ; then
-						less $logdir/smtpd/current
+						(
+						echo "$logdir/smtpd/current"
+						cat $logdir/smtpd/current
+						echo ----------------------
+						echo "$logdir/qmail-send/current"
+						cat $logdir/qmail-send/current
+						)
 					fi
 					printf "  testing SMTP AUTH %-18s (%s) hash=%-8s %-7s using swk %s failed\n"    "$i" "$str" "$hash" "$type" "$1"
 					[ -z "$failed" ] && failed="swaks-SMTP-AUTH-$i-hash-$hash" || failed="$failed, swaks-SMTP-AUTH-$i-hash-$hash"
@@ -1210,7 +1216,13 @@ do_smtp_auth_swaks()
 			else
 				fcount=$(expr $fcount + 1)
 				if [ $prompt -eq 1 ] ; then
-					less $logdir/qmail-send/current
+					(
+					echo "$logdir/smtpd/current"
+					cat $logdir/smtpd/current
+					echo ----------------------
+					echo "$logdir/qmail-send/current"
+					cat $logdir/qmail-send/current
+					)
 				fi
 				echo "  testing mail delivery in do_smtp_auth_swaks failed - SMTP AUTH $i"
 				[ -z "$failed" ] && failed="check_mail $maildir swaks-SMTP-AUTH-$i-hash-$hash" || failed="$failed, check_mail $maildir swaks-SMTP-AUTH-$i-hash-$hash"
@@ -2257,7 +2269,7 @@ do_eliminate_dups()
 {
 	destdir1=$($sudo $setuidgid indimail envdir $servicedir/smtpd/variables vuserinfo -d $1 | awk '{print $3}')
 	tm1=$(date +"%s.%4N")
-	echo "Starting duplicate eliminator test"
+	echo "Starting Duplicate Eliminator tests"
 	echo  1 > $servicedir/qmail-send.2025/variables/ELIMINATE_DUPS
 	echo 60 > $servicedir/qmail-send.2025/variables/ELIMINATE_DUPS_INT
 	echo "/bin/822header -X Received -X Delivered-To -X X-Delivered-To -X Date -X Message-ID" \
@@ -2270,19 +2282,44 @@ do_eliminate_dups()
 	sleep 1
 	do_qmail_inject $user $user@$HOSTNAME $1 # send email to testuser1 from $user@$HOSTNAME
 	count1=$(sudo ls $destdir1/Maildir/new | wc -l)
-	count2=$(sudo cat $destdir1/Maildir/dupmd5 | wc -l)
+	count2=$(sudo cat $destdir1/Maildir/dupmd5 2>/dev/null| wc -l)
 	if [ $count1 -eq $count2 -a $count1 -eq 1 ] ; then
 		tm2=$(date +"%s.%4N")
 		secs=$(echo $tm1 $tm2 $sleep_int 2 | awk '{printf("%0.4f\n", $2-$1-$3-$4)}')
 		tcount=$(expr $tcount + 1)
-		printf "\r  testing duplicate mail eliminator succeeded %67s [%.4f sec]\n" " " $secs
+		printf "\r  testing duplicate mail eliminator in vdelivermail succeeded %51s [%.4f sec]\n" " " $secs
 		print_pct
 	else
 		fcount=$(expr $fcount + 1)
 		echo "  testing duplicate mail eliminator failed"
-		[ -z "$failed" ] && failed="duplicate eliminator" || failed="$failed, duplicate eliminator"
+		[ -z "$failed" ] && failed="duplicate eliminator vdelivermail" || failed="$failed, duplicate eliminator vdelivermail"
 		[ $continue_on_err -eq 0 ] && exit 1 || return 0
 	fi
+	check_mail indimail $destdir1/Maildir
+
+	tm1=$(date +"%s.%4N")
+	echo "|/bin/ismaildup $maildir /bin/maildirdeliver $maildir" > $testdir/$user/.qmail
+	do_qmail_inject $user $user@$HOSTNAME $user@$HOSTNAME # send email to $user from $user@$HOSTNAME
+	sleep 1
+	do_qmail_inject $user $user@$HOSTNAME $user@$HOSTNAME # send email to $user from $user@$HOSTNAME
+	sleep 1
+	do_qmail_inject $user $user@$HOSTNAME $user@$HOSTNAME # send email to $user from $user@$HOSTNAME
+	count1=$(sudo ls $maildir/new | wc -l)
+	count2=$(sudo cat $maildir/dupmd5 | wc -l)
+	if [ $count1 -eq $count2 -a $count1 -eq 1 ] ; then
+		tm2=$(date +"%s.%4N")
+		secs=$(echo $tm1 $tm2 2 | awk '{printf("%0.4f\n", $2-$1-$3)}')
+		tcount=$(expr $tcount + 1)
+		printf "\r  testing duplicate mail eliminator in ismaildup succeeded %54s [%.4f sec]\n" " " $secs
+		print_pct
+	else
+		fcount=$(expr $fcount + 1)
+		echo "  testing duplicate mail eliminator failed"
+		[ -z "$failed" ] && failed="duplicate eliminator ismaildup" || failed="$failed, duplicate eliminator ismaildup"
+		[ $continue_on_err -eq 0 ] && exit 1 || return 0
+	fi
+	check_mail $user $maildir
+	/bin/rm -f $testdir/$user/.qmail
 }
 
 run_vcfilter()
@@ -3048,7 +3085,7 @@ current_dir=$(pwd)
 if [ -f $testdir/itotal.count ] ; then
 	total_tests=$(cat $testdir/itotal.count)
 else
-	total_tests=1089
+	total_tests=1091
 fi
 if [ -x /usr/bin/mariadb ] ; then
 	mysql=/usr/bin/mariadb
@@ -3137,6 +3174,9 @@ exit 0
 
 #
 # $Log: testindimail-virtual,v $
+# Revision 1.17  2023-10-23 18:47:37+05:30  Cprogrammer
+# added test for ismaildup
+#
 # Revision 1.16  2023-10-22 22:37:00+05:30  Cprogrammer
 # added test for duplicate eliminiator
 #
