added test for duplicate eliminator

diff --git a/indimail-x/tests/testindimail-virtual b/indimail-x/tests/testindimail-virtual
--- a/indimail-x/tests/testindimail-virtual
+++ b/indimail-x/tests/testindimail-virtual
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: testindimail-virtual,v 1.15 2023-10-08 01:47:46+05:30 Cprogrammer Exp mbhangui $
+# $Id: testindimail-virtual,v 1.16 2023-10-22 22:37:00+05:30 Cprogrammer Exp mbhangui $
 #
 start=$(date +'%s')
 user=$(whoami)
@@ -2253,6 +2253,38 @@ do_autoresponder()
 	fi
 }
 
+do_eliminate_dups()
+{
+	destdir1=$($sudo $setuidgid indimail envdir $servicedir/smtpd/variables vuserinfo -d $1 | awk '{print $3}')
+	tm1=$(date +"%s.%4N")
+	echo "Starting duplicate eliminator test"
+	echo  1 > $servicedir/qmail-send.2025/variables/ELIMINATE_DUPS
+	echo 60 > $servicedir/qmail-send.2025/variables/ELIMINATE_DUPS_INT
+	echo "/bin/822header -X Received -X Delivered-To -X X-Delivered-To -X Date -X Message-ID" \
+		> $servicedir/qmail-send.2025/variables/ELIMINATE_DUPS_ARGS
+	sudo svc -r $servicedir/qmail-send.2025
+	sleep $sleep_int
+	do_qmail_inject $user $user@$HOSTNAME $1 # send email to testuser1 from $user@$HOSTNAME
+	sleep 1
+	do_qmail_inject $user $user@$HOSTNAME $1 # send email to testuser1 from $user@$HOSTNAME
+	sleep 1
+	do_qmail_inject $user $user@$HOSTNAME $1 # send email to testuser1 from $user@$HOSTNAME
+	count1=$(sudo ls $destdir1/Maildir/new | wc -l)
+	count2=$(sudo cat $destdir1/Maildir/dupmd5 | wc -l)
+	if [ $count1 -eq $count2 -a $count1 -eq 1 ] ; then
+		tm2=$(date +"%s.%4N")
+		secs=$(echo $tm1 $tm2 $sleep_int 2 | awk '{printf("%0.4f\n", $2-$1-$3-$4)}')
+		tcount=$(expr $tcount + 1)
+		printf "\r  testing duplicate mail eliminator succeeded %67s [%.4f sec]\n" " " $secs
+		print_pct
+	else
+		fcount=$(expr $fcount + 1)
+		echo "  testing duplicate mail eliminator failed"
+		[ -z "$failed" ] && failed="duplicate eliminator" || failed="$failed, duplicate eliminator"
+		[ $continue_on_err -eq 0 ] && exit 1 || return 0
+	fi
+}
+
 run_vcfilter()
 {
 	$sudo env - \
@@ -2437,7 +2469,7 @@ do_scram_user_tests()
 		done
 		delete_user $testuser1
 		delete_user $testuser2
-		printf "\r  testing SMTP AUTH, IMAP/POP3 login, GSASL tests for hash $hash scram users succeeded"
+		printf "\r  testing SMTP AUTH, IMAP/POP3 login, GSASL tests for hash $hash scram users succeeded\n"
 	done
 	tcount=$(expr $tcount + 3)
 	printf "  testing command tcpserver non-encrypted succeeded\n"
@@ -3061,6 +3093,9 @@ printf "\r%126s\n" " "
 do_autoresponder $testuser1 $testuser2
 
 printf "\r%126s\n" " "
+do_eliminate_dups $testuser1
+
+printf "\r%126s\n" " "
 do_valias $testuser1 $testuser2
 delete_user $testuser1 >/dev/null 2>&1
 delete_user $testuser2 >/dev/null 2>&1
@@ -3102,6 +3137,9 @@ exit 0
 
 #
 # $Log: testindimail-virtual,v $
+# Revision 1.16  2023-10-22 22:37:00+05:30  Cprogrammer
+# added test for duplicate eliminiator
+#
 # Revision 1.15  2023-10-08 01:47:46+05:30  Cprogrammer
 # added test count and pct completed
 #
