create_rpm: build spec file before rpm build

diff --git a/indimail-x/create_rpm b/indimail-x/create_rpm
--- a/indimail-x/create_rpm
+++ b/indimail-x/create_rpm
@@ -69,9 +69,9 @@ else
 	rpmbuild=$HOME/rpmbuild
 fi
 
-make
+make -s indimail.spec
 if [ $? -ne 0 ] ; then
-	echo "make failed"
+	echo "make failed" 1>&2
 	exit 0
 fi
 if [ -d ../stage ] ; then
