fixed ircube build

diff --git a/ircube-1.0/create_rpm b/ircube-1.0/create_rpm
--- a/ircube-1.0/create_rpm
+++ b/ircube-1.0/create_rpm
@@ -1,18 +1,116 @@
 #!/bin/sh
-set -x
 rcsflag=0
-make clean
-make distclean
-/bin/rm -r autom4te.cache
-ver=1.0
-mv debian ../ircubeDebian
-cd ..
-if [ -f $HOME/.rpmmacros ] ; then
-	topdir=`grep ^%_topdir $HOME/.rpmmacros|awk '{print $2}'`
+version=1.0
+if test -f $HOME/.rpmmacros
+then
+	topdir=`grep ^%_topdir $HOME/.rpmmacros | awk '{print $2}'`
+	if test -n "$topdir"
+	then
+		rpmbuild=$topdir
+	else
+		rpmbuild=$HOME/rpmbuild
+	fi
 else
-	topdir=$HOME/rpmbuild
+	rpmbuild=$HOME/rpmbuild
 fi
-tar cf - ircube-$ver |gzip -c > $topdir/SOURCES/ircube-$ver.tar.gz
-mv ircubeDebian ircube-$ver/debian
-cd ircube-$ver
-rpmbuild -bb --clean ircube.spec
+
+copy_src=0
+echo -n "Copy Source Files - "
+read key
+if [ " $key" = " y" -o " $key" = " Y" ] ; then
+	copy_src=1
+fi
+
+make -s ircube.spec
+if [ $? -ne 0 ] ; then
+	echo "make failed" 1>&2
+	exit 0
+fi
+
+if [ $copy_src -eq 1 ] ; then
+	if [ -d ../stage ] ; then
+		/bin/rm -rf ../stage
+	fi
+	mkdir ../stage
+	echo "Versioning ircube-$version"
+	cp -rp . ../stage/ircube-$version
+	cd ../stage/ircube-$version
+	make -s clean
+	make -s distclean
+	/bin/rm -rf autom4te.cache
+	cd ..
+	echo "Archiving "ircube"-"$version".tar.gz in `pwd`"
+	tar \
+		--exclude=""ircube"-"$version"/.git" \
+		--exclude=""ircube"-"$version"/debian"  \
+		--exclude=""ircube"-"$version"/RCS" \
+		-cf - ircube-$version \
+		| gzip -c > $rpmbuild/SOURCES/"ircube"-"$version".tar.gz
+	cd ..
+	echo "Clearing stage directory"
+	/bin/rm -rf stage
+else
+	cd ..
+fi
+echo -n "Build RPM for ircube-"$version"-1."$release" (Y/N) - "
+read key
+if [ " $key" = " Y" -o " $key" = " y" ] ; then
+	dist=`uname -r |cut -d . -f4`
+	if [ $# -gt 0 ] ; then
+		release=$1
+	else
+		if [ -f /usr/share/roundcubemail/plugins/iwebadmin ] ; then
+			bdist=$(rpm -qf /usr/share/roundcubemail/plugins/iwebadmin|cut -d- -f3|cut -d. -f3)
+			if [ " $dist" = " $bdist" ] ; then
+				bversion=$(rpm -qf /etc/indimail/wordlist.db|cut -d- -f2)
+				if [ "$bversion" = "$version" ] ; then
+					release=$(rpm -qf /etc/indimail/wordlist.db |cut -d- -f3|cut -d. -f2)
+					release=$(expr $release + 1)
+				else
+					release=1
+				fi
+			else
+				release=1
+			fi
+		else
+			release=1
+		fi
+	fi
+	tmprel=`cat ircube-$version/conf-release 2>/dev/null`
+	if [ ! " $tmprel" = " 1.$release" ] ; then
+		echo 1.$release > ircube-$version/conf-release
+		cd ircube-$version
+		make ircube.spec
+		cp ircube.spec /tmp
+		cd debian
+		make
+		cd ../..
+	else
+		cp ircube-$version/ircube.spec /tmp
+	fi
+	rpmbuild -ba --clean /tmp/ircube.spec
+	/bin/rm -f /tmp/ircube.spec
+	build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
+	rpm --addsign $rpmbuild/RPMS/$build_arch/ircube-"$version"-"1.$release".$dist.$build_arch.rpm
+	rpm --addsign $rpmbuild/SRPMS/ircube-"$version"-"1.$release".$dist.src.rpm
+	echo -n "RPM lint for ircube-"$version"-1."$release" (Y/N) - "
+	read key
+	if [ " $key" = " Y" -o " $key" = " y" ] ; then
+		(
+		echo ircube
+		rpmlint $rpmbuild/RPMS/$build_arch/ircube-"$version"-"1.$release".$dist.$build_arch.rpm
+		echo ------------------------
+		echo ircube-"$version"-"1.$release".$dist.src.rpm
+		rpmlint $rpmbuild/SRPMS/ircube-"$version"-"1.$release".$dist.src.rpm
+		echo ------------------------
+		) 2>&1 | less
+	fi
+fi
+if [ $copy_src -eq 1 ] ; then
+	echo -n "Remove Source (Y/N) - "
+	read key
+	if [ " $key" = " Y" -o " $key" = " y" ] ; then
+		echo "/bin/rm -f $rpmbuild/SOURCES/ircube-$version"
+		/bin/rm -f $rpmbuild/SOURCES/ircube-$version
+	fi
+fi
