multiple fixes for openSUSE

diff --git a/ircube-1.0/roundcube_config b/ircube-1.0/roundcube_config
--- a/ircube-1.0/roundcube_config
+++ b/ircube-1.0/roundcube_config
@@ -60,7 +60,11 @@ echo "    'sauserprefs',"
 echo "    'markasjunk2',"
 echo "    'iwebadmin',"
 echo ");"
+if [ $is_suse -eq 1 ] ; then
+echo "\$config['skin'] = 'elastic';"
+else
 echo "\$config['skin'] = 'larry';"
+fi
 }
 
 create_roundcube_httpd_conf()
@@ -258,9 +262,9 @@ fi
 
 # RoundCube DB setup
 if [ $is_suse -eq 1 ] ; then
-	httpd_base=/srv
+	rcube_base=/srv/www/roundcubemail
 else
-	httpd_base=/usr
+	rcube_base=/usr/share/roundcubemail
 fi
 echo "Creating MySQL DB for roundcube"
 if [ ! -d /var/indimail/mysqldb/data/RoundCube_db ] ; then
@@ -309,9 +313,9 @@ if [ ! -d /var/indimail/mysqldb/data/RoundCube_db ] ; then
 			echo "GRANT ALL PRIVILEGES ON RoundCube_db.* TO roundcube;"
 			echo "FLUSH PRIVILEGES;"
 		) | /usr/bin/mysql -u mysql -p"$PRIV_PASS" mysql
-		if [ -f $httpd_base/share/roundcubemail/SQL/mysql.initial.sql ] ; then
+		if [ -f $rcube_base/SQL/mysql.initial.sql ] ; then
 			echo "initializing roundcube db"
-			/usr/bin/mysql -u roundcube -psubscribed RoundCube_db < $httpd_base/share/roundcubemail/SQL/mysql.initial.sql
+			/usr/bin/mysql -u roundcube -psubscribed RoundCube_db < $rcube_base/SQL/mysql.initial.sql
 		fi
 		if [ -x /service/mysql.3306/shutdown ] ; then
 			/service/mysql.3306/shutdown
@@ -329,7 +333,7 @@ if [ -f /etc/debian_version ] ; then
 	php_ini="ls /etc/php/*/apache2/php.ini"
 elif [ $is_suse -eq 1 ] ; then
 	httpd_user="wwwrun"
-	httpd_group="wwwrun"
+	httpd_group="www"
 	php_ini="/etc/php7/apache2/php.ini"
 else
 	# CentOS, Fedora
@@ -340,6 +344,11 @@ fi
 
 # same for all distros
 # RoundCube DB setup
+if [ $is_suse -eq 1 -a -f /etc/roundcubemail/config.inc.php ] ; then
+	if [ ! -f /etc/roundcubemail/config.inc.php.orig ] ; then
+		$mv /etc/roundcubemail/config.inc.php /etc/roundcubemail/config.inc.php.orig
+	fi
+fi
 if [ -d /etc/roundcubemail -a ! -f /etc/roundcubemail/config.inc.php ] ; then
 	echo "creating /etc/roundcubemail/config.inc.php"
 	create_roundcube_php_config > /tmp/config.cnf.$$
@@ -432,7 +441,7 @@ else
 	ssl_cnf=""
 fi
 
-if [ -n "$ssl_cnf" -f $ssl_cnf ] ; then
+if [ -n "$ssl_cnf" -a -f $ssl_cnf ] ; then
 	echo "configuring $ssl_cnf"
 	$mv $ssl_cnf $ssl_cnf.BAK
 	$cp $ssl_cnf.BAK $ssl_cnf
@@ -563,6 +572,8 @@ fi
 #
 if [ -f /etc/php-fpm.d/www.conf ] ; then
 	php_fpm_www_conf=/etc/php-fpm.d/www.conf
+elif [ -f /etc/php7/fpm/php-fpm.d/www.conf.default ] ; then
+	php_fpm_www_conf=/etc/php7/fpm/php-fpm.d/www.conf
 elif [ -f /etc/php7/fpm/php-fpm.d/www.conf ] ; then
 	php_fpm_www_conf=/etc/php7/fpm/php-fpm.d/www.conf
 else #debian /etc/php/7.3/fpm/pool.d/www.conf
@@ -572,20 +583,23 @@ if [ $is_suse -eq 1 ] ; then
 	if [ -f /etc/php7/fpm/php-fpm.conf.default ] ; then
 		$cp /etc/php7/fpm/php-fpm.conf.default /etc/php7/fpm/php-fpm.conf
 	fi
-	echo "fixing /etc/php7/fpm/php-fpm.conf"
-	$sed -i -e "s{^;pid =.*{pid = /run/php-fpm.pid{g" \
-		/etc/php7/fpm/php-fpm.conf
-	if [ -f $php_fpm_www_conf.default ] ; then
-		$cp $php_fpm_www_conf.default $php_fpm_www_conf
+	if [ -f /etc/php7/fpm/php-fpm.conf ] ; then
+		echo "fixing /etc/php7/fpm/php-fpm.conf"
+		$sed -i -e "s{^;pid =.*{pid = /run/php-fpm.pid{g" \
+			/etc/php7/fpm/php-fpm.conf
+	fi
+	if [ -f "$php_fpm_www_conf".default ] ; then
+		$cp "$php_fpm_www_conf".default $php_fpm_www_conf
 	fi
 
-	if [ -f /etc/apache2/loadmodule.conf ] ; then
-		grep php7_mode /etc/apache2/loadmodule.conf > /dev/null
-		if [ $? -ne 0 ] ; then
-			echo "fixing /etc/apache2/loadmodule.conf"
-			echo "LoadModule php7_module                    /usr/lib64/apache2/mod_php7.so" > /etc/apache2/loadmodule.conf
-		fi
-	fi
+	#if [ -f /etc/apache2/loadmodule.conf ] ; then
+	#	grep php7_module /etc/apache2/loadmodule.conf > /dev/null
+	#	if [ $? -ne 0 ] ; then
+	#		echo "fixing /etc/apache2/loadmodule.conf"
+	#		echo "LoadModule php7_module /usr/lib64/apache2/mod_php7.so" \
+	#			> /etc/apache2/loadmodule.conf
+	#	fi
+	#fi
 fi
 if [ -f $php_fpm_www_conf ] ; then
 	echo "fixing $php_fpm_www_conf"
@@ -605,10 +619,6 @@ if [ ! -d /service/php-fpm ] ; then
 		sockname=$(grep "listen =" $php_fpm_www_conf |cut -d= -f2)
 		sockdir=$(dirname $sockname)
 		echo "socket directory for php-fpm is $sockdir"
-	else
-		echo "couldn't find socket dir for php-fpm"
-	fi
-	if [ -n "$php_fpm_www_conf" -a -f "$php_fpm_www_conf" ] ; then
 		echo "Creating supervised service for php-fpm"
 		mkdir -p /service/php-fpm/log
 		touch /service/php-fpm/down
@@ -627,6 +637,8 @@ if [ ! -d /service/php-fpm ] ; then
 		echo "  /usr/sbin/multilog t /var/log/svc/php-fpm"
 		) > /service/php-fpm/log/run
 		chmod +x /service/php-fpm/log/run
+	else
+		echo "couldn't find php-fpm"
 	fi
 fi
 
@@ -658,16 +670,15 @@ if [ -x /usr/bin/crontab ] ; then
 	tmp=$(mktemp -t crontab.tmp.XXXXXXXXXX)
 	echo "Getting existing crontab entry for root"
 	crontab -u root -l 2>/dev/null | \
-		$sed "/$(echo $httpd_base/share/roundcubemail | \
-		$sed -e 's/\//\\\//g')\/bin\/cleandb\.sh/d" > "${tmp}"
-	echo "18 11 * * * $httpd_base/share/roundcubemail/bin/cleandb.sh > /dev/null" >> "${tmp}"
+		$sed "/$(echo $rcube_base| $sed -e 's/\//\\\//g')\/bin\/cleandb\.sh/d" > "${tmp}"
+	echo "18 11 * * * $rcube_base/bin/cleandb.sh > /dev/null" >> "${tmp}"
 	echo "Adding crontab entry for root"
 	crontab -u root "${tmp}"
 	$rm -f "${tmp}"
 	unset tmp
-	$chmod +x $httpd_base/share/roundcubemail/bin/cleandb.sh
+	$chmod +x $rcube_base/share/roundcubemail/bin/cleandb.sh
 fi
 
 echo "Adding qmail as supplementary group to $httpd_group"
-/usr/bin/getent group $httpd_group && /usr/sbin/usermod -aG qmail $httpd_group
+/usr/bin/getent passwd $httpd_user >/dev/null && /usr/sbin/usermod -aG qmail $httpd_user
 exit 0
