added command line option to set verbose rpmbuild

diff --git a/indium-x/create_rpm b/indium-x/create_rpm
--- a/indium-x/create_rpm
+++ b/indium-x/create_rpm
@@ -2,6 +2,34 @@
 curdir=`pwd`
 version=$(cat conf-version)
 
+if [ -f /etc/debian_version ] ; then
+	echo "you can't do rpmbuild on an insane system" 1>&2
+	exit 1
+fi
+
+verbose=0
+while test $# -gt 0; do
+    case "$1" in
+    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
+	;;
+    *) optarg=
+	;;
+    esac
+
+    case "$1" in
+    --verbose)
+	verbose=1
+    ;;
+    *)
+    echo "invalid option [$1]"
+    read key
+    usage 1
+    ;;
+    esac
+
+    shift
+done
+
 if test -f $HOME/.rpmmacros
 then
 	topdir=`grep ^%_topdir $HOME/.rpmmacros | awk '{print $2}'`
@@ -94,23 +122,32 @@ if [ " $key" = " Y" -o " $key" = " y" ] ; then
 		make -s -C indium-x indium.spec
 		cp indium-x/indium.spec /tmp
 	fi
-	echo "rpmbuild -ba --clean --quiet /tmp/indium.spec"
-	rpmbuild -ba --clean --quiet /tmp/indium.spec
-	/bin/rm -f /tmp/indium.spec
-	build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
-	rpm --addsign $rpmbuild/RPMS/$build_arch/indium-"$version"-"1.$release".$dist.$build_arch.rpm
-	rpm --addsign $rpmbuild/SRPMS/indium-"$version"-"1.$release".$dist.src.rpm
-	echo -n "RPM lint for indium-"$version"-1."$release" (Y/N) - "
-	read key
-	if [ " $key" = " Y" -o " $key" = " y" ] ; then
-		(
-		echo indium
-		rpmlint $rpmbuild/RPMS/$build_arch/indium-"$version"-"1.$release".$dist.$build_arch.rpm
-		echo ------------------------
-		echo indium-"$version"-"1.$release".$dist.src.rpm
-		rpmlint $rpmbuild/SRPMS/indium-"$version"-"1.$release".$dist.src.rpm
-		echo ------------------------
-		) 2>&1 | less
+	if [ $verbose -eq 0 ] ; then
+		echo "rpmbuild -ba --clean --quiet /tmp/indium.spec"
+		rpmbuild -ba --clean --quiet /tmp/indium.spec
+	else
+		echo "rpmbuild -ba --clean /tmp/indium.spec"
+		rpmbuild -ba --clean /tmp/indium.spec
+	fi
+	if [ $? -eq 0 ] ; then
+		/bin/rm -f /tmp/indium.spec
+		build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
+		rpm --addsign $rpmbuild/RPMS/$build_arch/indium-"$version"-"1.$release".$dist.$build_arch.rpm
+		rpm --addsign $rpmbuild/SRPMS/indium-"$version"-"1.$release".$dist.src.rpm
+		echo -n "RPM lint for indium-"$version"-1."$release" (Y/N) - "
+		read key
+		if [ " $key" = " Y" -o " $key" = " y" ] ; then
+			(
+			echo indium
+			rpmlint $rpmbuild/RPMS/$build_arch/indium-"$version"-"1.$release".$dist.$build_arch.rpm
+			echo ------------------------
+			echo indium-"$version"-"1.$release".$dist.src.rpm
+			rpmlint $rpmbuild/SRPMS/indium-"$version"-"1.$release".$dist.src.rpm
+			echo ------------------------
+			) 2>&1 | less
+		fi
+	else
+		/bin/rm -f /tmp/indium.spec
 	fi
 fi
 if [ $copy_src -eq 1 ] ; then
