added command line option to set verbose rpmbuild

diff --git a/bogofilter-x/create_rpm b/bogofilter-x/create_rpm
--- a/bogofilter-x/create_rpm
+++ b/bogofilter-x/create_rpm
@@ -6,6 +6,34 @@
 curdir=`pwd`
 version=$(cat conf-version)
 
+if [ -f /etc/debian_version ] ; then
+	echo "you can't do rpmbuild on an insane system" 1>&2
+	exit 1
+fi
+
+verbose=0
+while test $# -gt 0; do
+    case "$1" in
+    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
+	;;
+    *) optarg=
+	;;
+    esac
+
+    case "$1" in
+    --verbose)
+	verbose=1
+    ;;
+    *)
+    echo "invalid option [$1]"
+    read key
+    usage 1
+    ;;
+    esac
+
+    shift
+done
+
 if test -f $HOME/.rpmmacros
 then
 	topdir=`grep ^%_topdir $HOME/.rpmmacros | awk '{print $2}'`
@@ -99,23 +127,32 @@ if [ " $key" = " Y" -o " $key" = " y" ] ; then
 	else
 		cp bogofilter-x/indimail-spamfilter.spec /tmp
 	fi
-	echo "rpmbuild -ba --clean --quiet /tmp/indimail-spamfilter.spec"
-	rpmbuild -ba --clean --quiet /tmp/indimail-spamfilter.spec
-	#/bin/rm -f /tmp/indimail-spamfilter.spec
-	build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
-	rpm --addsign $rpmbuild/RPMS/$build_arch/indimail-spamfilter-"$version"-"1.$release".$dist.$build_arch.rpm
-	rpm --addsign $rpmbuild/SRPMS/indimail-spamfilter-"$version"-"1.$release".$dist.src.rpm
-	echo -n "RPM lint for indimail-spamfilter-"$version"-1."$release" (Y/N) - "
-	read key
-	if [ " $key" = " Y" -o " $key" = " y" ] ; then
-		(
-		echo indimail-spamfilter
-		rpmlint $rpmbuild/RPMS/$build_arch/indimail-spamfilter-"$version"-"1.$release".$dist.$build_arch.rpm
-		echo ------------------------
-		echo indimail-spamfilter-"$version"-"1.$release".$dist.src.rpm
-		rpmlint $rpmbuild/SRPMS/indimail-spamfilter-"$version"-"1.$release".$dist.src.rpm
-		echo ------------------------
-		) 2>&1 | less
+	if [ $verbose -eq 0 ] ; then
+		echo "rpmbuild -ba --clean --quiet /tmp/indimail-spamfilter.spec"
+		rpmbuild -ba --clean --quiet /tmp/indimail-spamfilter.spec
+	else
+		echo "rpmbuild -ba --clean /tmp/indimail-spamfilter.spec"
+		rpmbuild -ba --clean /tmp/indimail-spamfilter.spec
+	fi
+	if [ $? -q 0 ] ; then
+		/bin/rm -f /tmp/indimail-spamfilter.spec
+		build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
+		rpm --addsign $rpmbuild/RPMS/$build_arch/indimail-spamfilter-"$version"-"1.$release".$dist.$build_arch.rpm
+		rpm --addsign $rpmbuild/SRPMS/indimail-spamfilter-"$version"-"1.$release".$dist.src.rpm
+		echo -n "RPM lint for indimail-spamfilter-"$version"-1."$release" (Y/N) - "
+		read key
+		if [ " $key" = " Y" -o " $key" = " y" ] ; then
+			(
+			echo indimail-spamfilter
+			rpmlint $rpmbuild/RPMS/$build_arch/indimail-spamfilter-"$version"-"1.$release".$dist.$build_arch.rpm
+			echo ------------------------
+			echo indimail-spamfilter-"$version"-"1.$release".$dist.src.rpm
+			rpmlint $rpmbuild/SRPMS/indimail-spamfilter-"$version"-"1.$release".$dist.src.rpm
+			echo ------------------------
+			) 2>&1 | less
+		fi
+	else
+		/bin/rm -f /tmp/indimail-spamfilter.spec
 	fi
 fi
 
