create_rpm - option to bypass copying of source Makefile.am - use conf-release in sed command using backquote operator configure.ac - removed setting release from conf-release

diff --git a/bogofilter-x/create_rpm b/bogofilter-x/create_rpm
--- a/bogofilter-x/create_rpm
+++ b/bogofilter-x/create_rpm
@@ -19,31 +19,50 @@ else
 	rpmbuild=$HOME/rpmbuild
 fi
 
-if [ -d ../stage ] ; then
-	/bin/rm -rf ../stage
+copy_src=0
+echo -n "Copy Source Files - "
+read key
+if [ " $key" = " y" -o " $key" = " Y" ] ; then
+	copy_src=1
 fi
-mkdir ../stage
-cd ..
-echo "Versioning indimail-spamfilter-$version"
-cp -rp bogofilter-x stage/indimail-spamfilter-$version
-cd stage/indimail-spamfilter-$version
-echo "Cleaning indimail-spamfilter-$version"
-make -s clean > /dev/null
-make -s distclean > /dev/null
-/bin/rm -rf autom4te.cache .deps
-cd ..
-echo "Archiving indimail-spamfilter-$version.tar.bz2 in `pwd`"
-tar \
-	--exclude="indimail-spamfilter-$version/.git" \
-	--exclude="indimail-spamfilter-$version/debian"  \
-	--exclude="indimail-spamfilter-$version/RCS" \
-	-cf - indimail-spamfilter-"$version" \
-	| bzip2 -c > $rpmbuild/SOURCES/indimail-spamfilter-"$version".tar.bz2
-for i in rpmlintrc permissions.easy permissions.secure permissions.paranoid
-do
-	echo "cp -p indimail-spamfilter-$version/indimail-spamfilter-$i $rpmbuild/SOURCES"
-	cp -p indimail-spamfilter-$version/indimail-spamfilter-$i $rpmbuild/SOURCES
-done
+make -s indimail-spamfilter.spec
+if [ $? -ne 0 ] ; then
+	echo "make failed" 1>&2
+	exit 1
+fi
+
+if [ $copy_src -eq 1 ] ; then
+	if [ -d ../stage ] ; then
+		/bin/rm -rf ../stage
+	fi
+	mkdir ../stage
+	cd ..
+	echo "Versioning indimail-spamfilter-$version"
+	cp -rp bogofilter-x stage/indimail-spamfilter-$version
+	cd stage/indimail-spamfilter-$version
+	echo "Cleaning indimail-spamfilter-$version"
+	make -s clean > /dev/null
+	make -s distclean > /dev/null
+	/bin/rm -rf autom4te.cache .deps
+	cd ..
+	echo "Archiving indimail-spamfilter-$version.tar.bz2 in `pwd`"
+	tar \
+		--exclude="indimail-spamfilter-$version/.git" \
+		--exclude="indimail-spamfilter-$version/debian"  \
+		--exclude="indimail-spamfilter-$version/RCS" \
+		-cf - indimail-spamfilter-"$version" \
+		| bzip2 -c > $rpmbuild/SOURCES/indimail-spamfilter-"$version".tar.bz2
+	for i in rpmlintrc permissions.easy permissions.secure permissions.paranoid
+	do
+		echo "cp -p indimail-spamfilter-$version/indimail-spamfilter-$i $rpmbuild/SOURCES"
+		cp -p indimail-spamfilter-$version/indimail-spamfilter-$i $rpmbuild/SOURCES
+	done
+	cd ..
+	echo "Clearing stage directory"
+	/bin/rm -rf stage
+else
+	cd ..
+fi
 dist=`uname -r |cut -d . -f4`
 if [ $# -gt 0 ] ; then
 	release=$1
@@ -65,9 +84,6 @@ else
 		release=1
 	fi
 fi
-cd ..
-echo "Clearing stage directory"
-/bin/rm -rf stage
 echo -n "Build RPM for indimail-spamfilter-"$version"-1."$release" (Y/N) - "
 read key
 if [ " $key" = " Y" -o " $key" = " y" ] ; then
@@ -84,7 +100,7 @@ if [ " $key" = " Y" -o " $key" = " y" ] ; then
 		cp bogofilter-x/indimail-spamfilter.spec /tmp
 	fi
 	rpmbuild -ba --clean /tmp/indimail-spamfilter.spec
-	/bin/rm -f /tmp/indimail-spamfilter.spec
+	#/bin/rm -f /tmp/indimail-spamfilter.spec
 	build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
 	rpm --addsign $rpmbuild/RPMS/$build_arch/indimail-spamfilter-"$version"-"1.$release".$dist.$build_arch.rpm
 	rpm --addsign $rpmbuild/SRPMS/indimail-spamfilter-"$version"-"1.$release".$dist.src.rpm
@@ -101,14 +117,17 @@ if [ " $key" = " Y" -o " $key" = " y" ] ; then
 		) 2>&1 | less
 	fi
 fi
-echo -n "Remove Source (Y/N) - "
-read key
-if [ " $key" = " Y" -o " $key" = " y" ] ; then
-	echo "/bin/rm -f $rpmbuild/SOURCES/indimail-spamfilter-$version.tar.bz2"
-	/bin/rm -f $rpmbuild/SOURCES/indimail-spamfilter-$version.tar.bz2
-	for i in rpmlintrc permissions.easy permissions.secure permissions.paranoid
-	do
-		echo "/bin/rm -f $rpmbuild/SOURCES/indimail-spamfilter-$i"
-		/bin/rm -f $rpmbuild/SOURCES/indimail-spamfilter-$i
-	done
+
+if [ $copy_src -eq 1 ] ; then
+	echo -n "Remove Source (Y/N) - "
+	read key
+	if [ " $key" = " Y" -o " $key" = " y" ] ; then
+		echo "/bin/rm -f $rpmbuild/SOURCES/indimail-spamfilter-$version.tar.bz2"
+		/bin/rm -f $rpmbuild/SOURCES/indimail-spamfilter-$version.tar.bz2
+		for i in rpmlintrc permissions.easy permissions.secure permissions.paranoid
+		do
+			echo "/bin/rm -f $rpmbuild/SOURCES/indimail-spamfilter-$i"
+			/bin/rm -f $rpmbuild/SOURCES/indimail-spamfilter-$i
+		done
+	fi
 fi
diff --git a/indium-x/create_rpm b/indium-x/create_rpm
--- a/indium-x/create_rpm
+++ b/indium-x/create_rpm
@@ -15,28 +15,48 @@ else
 	rpmbuild=$HOME/rpmbuild
 fi
 
-if [ -d ../stage ] ; then
-	/bin/rm -rf ../stage
+copy_src=0
+echo -n "Copy Source Files - "
+read key
+if [ " $key" = " y" -o " $key" = " Y" ] ; then
+	copy_src=1
 fi
-mkdir ../stage
-cd ..
-echo "Versioning indium-$version"
-cp -rp indium-x stage/indium-$version
-cd stage/indium-$version
-echo "Cleaning indium-$version"
-make -s clean > /dev/null
-make -s distclean > /dev/null
-/bin/rm -rf autom4te.cache .deps
-cd ..
-echo "Archiving indium-$version.tar.gz in `pwd`"
-tar \
-	--exclude="indium-$version/.git" \
-	--exclude="indium-$version/debian"  \
-	--exclude="indium-$version/RCS" \
+
+make -s indium.spec
+if [ $? -ne 0 ] ; then
+	echo "make failed" 1>&2
+	exit 0
+fi
+
+if [ $copy_src -eq 1 ] ; then
+	if [ -d ../stage ] ; then
+		/bin/rm -rf ../stage
+	fi
+	mkdir ../stage
+	cd ..
+	echo "Versioning indium-$version"
+	cp -rp indium-x stage/indium-$version
+	cd stage/indium-$version
+	echo "Cleaning indium-$version"
+	make -s clean > /dev/null
+	make -s distclean > /dev/null
+	/bin/rm -rf autom4te.cache .deps
+	cd ..
+	echo "Archiving indium-$version.tar.gz in `pwd`"
+	tar \
+		--exclude="indium-$version/.git" \
+		--exclude="indium-$version/debian"  \
+		--exclude="indium-$version/RCS" \
 	-cf - indium-"$version" \
-	| gzip -c > $rpmbuild/SOURCES/indium-"$version".tar.gz
-echo "cp indium-$version/indium-rpmlintrc $rpmbuild/SOURCES"
-cp indium-$version/indium-rpmlintrc $rpmbuild/SOURCES
+		| gzip -c > $rpmbuild/SOURCES/indium-"$version".tar.gz
+	echo "cp indium-$version/indium-rpmlintrc $rpmbuild/SOURCES"
+	cp indium-$version/indium-rpmlintrc $rpmbuild/SOURCES
+	cd ..
+	echo "Clearing stage directory"
+	/bin/rm -rf stage
+else
+	cd ..
+fi
 dist=`uname -r |cut -d . -f4`
 if [ $# -gt 0 ] ; then
 	release=$1
@@ -58,9 +78,6 @@ else
 		release=1
 	fi
 fi
-cd ..
-echo "Clearing stage directory"
-/bin/rm -rf stage
 echo -n "Build RPM for indium-"$version"-1."$release" (Y/N) - "
 read key
 if [ " $key" = " Y" -o " $key" = " y" ] ; then
@@ -95,11 +112,13 @@ if [ " $key" = " Y" -o " $key" = " y" ] ; then
 		) 2>&1 | less
 	fi
 fi
-echo -n "Remove Source (Y/N) - "
-read key
-if [ " $key" = " Y" -o " $key" = " y" ] ; then
-	echo "/bin/rm -f $rpmbuild/SOURCES/indium-$version.tar.bz2"
-	/bin/rm -f $rpmbuild/SOURCES/indium-$version.tar.bz2
-	echo "/bin/rm -f $rpmbuild/SOURCES/indium-rpmlintrc"
-	/bin/rm -f $rpmbuild/SOURCES/indium-rpmlintrc
+if [ $copy_src -eq 1 ] ; then
+	echo -n "Remove Source (Y/N) - "
+	read key
+	if [ " $key" = " Y" -o " $key" = " y" ] ; then
+		echo "/bin/rm -f $rpmbuild/SOURCES/indium-$version.tar.bz2"
+		/bin/rm -f $rpmbuild/SOURCES/indium-$version.tar.bz2
+		echo "/bin/rm -f $rpmbuild/SOURCES/indium-rpmlintrc"
+		/bin/rm -f $rpmbuild/SOURCES/indium-rpmlintrc
+	fi
 fi
diff --git a/iwebadmin-x/create_rpm b/iwebadmin-x/create_rpm
--- a/iwebadmin-x/create_rpm
+++ b/iwebadmin-x/create_rpm
@@ -14,32 +14,51 @@ then
 else
 	rpmbuild=$HOME/rpmbuild
 fi
-
-if [ -d ../stage ] ; then
-	/bin/rm -rf ../stage
+copy_src=0
+echo -n "Copy Source Files - "
+read key
+if [ " $key" = " y" -o " $key" = " Y" ] ; then
+	copy_src=1
 fi
-mkdir ../stage
-cd ..
-echo "Versioning iwebadmin-$version"
-cp -rp iwebadmin-x stage/iwebadmin-$version
-cd stage/iwebadmin-$version
-echo "Cleaning iwebadmin-$version"
-make -s clean > /dev/null
-make -s distclean > /dev/null
-/bin/rm -rf autom4te.cache .deps
-cd ..
-echo "Archiving iwebadmin-$version.tar.gz in `pwd`"
-tar \
-	--exclude="iwebadmin-$version/.git" \
-	--exclude="iwebadmin-$version/debian"  \
-	--exclude="iwebadmin-$version/RCS" \
-	-cf - iwebadmin-"$version" \
-	| gzip -c > $rpmbuild/SOURCES/iwebadmin-"$version".tar.gz
-for i in rpmlintrc permissions.easy permissions.secure permissions.paranoid
-do
-	echo "cp iwebadmin-$version/iwebadmin-$i $rpmbuild/SOURCES"
-	cp iwebadmin-$version/iwebadmin-$i $rpmbuild/SOURCES
-done
+
+make -s iwebadmin.spec
+if [ $? -ne 0 ] ; then
+	echo "make failed" 1>&2
+	exit 0
+fi
+
+if [ $copy_src -eq 1 ] ; then
+	if [ -d ../stage ] ; then
+		/bin/rm -rf ../stage
+	fi
+	mkdir ../stage
+	cd ..
+	echo "Versioning iwebadmin-$version"
+	cp -rp iwebadmin-x stage/iwebadmin-$version
+	cd stage/iwebadmin-$version
+	echo "Cleaning iwebadmin-$version"
+	make -s clean > /dev/null
+	make -s distclean > /dev/null
+	/bin/rm -rf autom4te.cache .deps
+	cd ..
+	echo "Archiving iwebadmin-$version.tar.gz in `pwd`"
+	tar \
+		--exclude="iwebadmin-$version/.git" \
+		--exclude="iwebadmin-$version/debian"  \
+		--exclude="iwebadmin-$version/RCS" \
+		-cf - iwebadmin-"$version" \
+		| gzip -c > $rpmbuild/SOURCES/iwebadmin-"$version".tar.gz
+	for i in rpmlintrc permissions.easy permissions.secure permissions.paranoid
+	do
+		echo "cp iwebadmin-$version/iwebadmin-$i $rpmbuild/SOURCES"
+		cp iwebadmin-$version/iwebadmin-$i $rpmbuild/SOURCES
+	done
+	cd ..
+	echo "Clearing stage directory"
+	/bin/rm -rf stage
+else
+	cd ..
+fi
 dist=`uname -r |cut -d . -f4`
 if [ $# -gt 0 ] ; then
 	release=$1
@@ -61,9 +80,6 @@ else
 		release=1
 	fi
 fi
-cd ..
-echo "Clearing stage directory"
-/bin/rm -rf stage
 echo -n "Build RPM for iwebadmin-"$version"-1."$release" (Y/N) - "
 read key
 if [ " $key" = " Y" -o " $key" = " y" ] ; then
@@ -98,14 +114,16 @@ if [ " $key" = " Y" -o " $key" = " y" ] ; then
 		) 2>&1 | less
 	fi
 fi
-echo -n "Remove Source (Y/N) - "
-read key
-if [ " $key" = " Y" -o " $key" = " y" ] ; then
-	echo "/bin/rm -f $rpmbuild/SOURCES/iwebadmin-$version.tar.bz2"
-	/bin/rm -f $rpmbuild/SOURCES/iwebadmin-$version.tar.bz2
-	for i in rpmlintrc permissions.easy permissions.secure permissions.paranoid
-	do
-		echo "/bin/rm -f $rpmbuild/SOURCES/iwebadmin-$i"
-		/bin/rm -f $rpmbuild/SOURCES/iwebadmin-$i
-	done
+if [ $copy_src -eq 1 ] ; then
+	echo -n "Remove Source (Y/N) - "
+	read key
+	if [ " $key" = " Y" -o " $key" = " y" ] ; then
+		echo "/bin/rm -f $rpmbuild/SOURCES/iwebadmin-$version.tar.bz2"
+		/bin/rm -f $rpmbuild/SOURCES/iwebadmin-$version.tar.bz2
+		for i in rpmlintrc permissions.easy permissions.secure permissions.paranoid
+		do
+			echo "/bin/rm -f $rpmbuild/SOURCES/iwebadmin-$i"
+			/bin/rm -f $rpmbuild/SOURCES/iwebadmin-$i
+		done
+	fi
 fi
diff --git a/logalert-x/create_rpm b/logalert-x/create_rpm
--- a/logalert-x/create_rpm
+++ b/logalert-x/create_rpm
@@ -14,29 +14,47 @@ then
 else
 	rpmbuild=$HOME/rpmbuild
 fi
-
-if [ -d ../stage ] ; then
-	/bin/rm -rf ../stage
+copy_src=0
+echo -n "Copy Source Files - "
+read key
+if [ " $key" = " y" -o " $key" = " Y" ] ; then
+	copy_src=1
 fi
-mkdir ../stage
-cd ..
-echo "Versioning logalert-$version"
-cp -rp logalert-x stage/logalert-$version
-cd stage/logalert-$version
-echo "Cleaning logalert-$version"
-make -s clean > /dev/null
-make -s distclean > /dev/null
-/bin/rm -rf autom4te.cache .deps
-cd ..
-echo "Archiving logalert-$version.tar.gz in `pwd`"
-tar \
-	--exclude="logalert-$version/.git" \
-	--exclude="logalert-$version/debian"  \
-	--exclude="logalert-$version/RCS" \
-	-cf - logalert-"$version" \
-	| gzip -c > $rpmbuild/SOURCES/logalert-"$version".tar.gz
-echo "cp logalert-$version/logalert-rpmlintrc $rpmbuild/SOURCES"
-cp logalert-$version/logalert-rpmlintrc $rpmbuild/SOURCES
+
+make -s logalert.spec
+if [ $? -ne 0 ] ; then
+	echo "make failed" 1>&2
+	exit 0
+fi
+if [ $copy_src -eq 1 ] ; then
+	if [ -d ../stage ] ; then
+		/bin/rm -rf ../stage
+	fi
+	mkdir ../stage
+	cd ..
+	echo "Versioning logalert-$version"
+	cp -rp logalert-x stage/logalert-$version
+	cd stage/logalert-$version
+	echo "Cleaning logalert-$version"
+	make -s clean > /dev/null
+	make -s distclean > /dev/null
+	/bin/rm -rf autom4te.cache .deps
+	cd ..
+	echo "Archiving logalert-$version.tar.gz in `pwd`"
+	tar \
+		--exclude="logalert-$version/.git" \
+		--exclude="logalert-$version/debian"  \
+		--exclude="logalert-$version/RCS" \
+		-cf - logalert-"$version" \
+		| gzip -c > $rpmbuild/SOURCES/logalert-"$version".tar.gz
+	echo "cp logalert-$version/logalert-rpmlintrc $rpmbuild/SOURCES"
+	cp logalert-$version/logalert-rpmlintrc $rpmbuild/SOURCES
+	cd ..
+	echo "Clearing stage directory"
+	/bin/rm -rf stage
+else
+	cd ..
+fi
 dist=`uname -r |cut -d . -f4`
 if [ $# -gt 0 ] ; then
 	release=$1
@@ -58,9 +76,6 @@ else
 		release=1
 	fi
 fi
-cd ..
-echo "Clearing stage directory"
-/bin/rm -rf stage
 echo -n "Build RPM for logalert-"$version"-1."$release" (Y/N) - "
 read key
 if [ " $key" = " Y" -o " $key" = " y" ] ; then
@@ -96,11 +111,13 @@ if [ " $key" = " Y" -o " $key" = " y" ] ; then
 		) 2>&1 | less
 	fi
 fi
-echo -n "Remove Source (Y/N) - "
-read key
-if [ " $key" = " Y" -o " $key" = " y" ] ; then
-	echo "/bin/rm -f $rpmbuild/SOURCES/logalert-$version.tar.bz2"
-	/bin/rm -f $rpmbuild/SOURCES/logalert-$version.tar.bz2
-	echo "/bin/rm -f $rpmbuild/SOURCES/logalert-rpmlintrc"
-	/bin/rm -f $rpmbuild/SOURCES/logalert-rpmlintrc
+if [ $copy_src -eq 1 ] ; then
+	echo -n "Remove Source (Y/N) - "
+	read key
+	if [ " $key" = " Y" -o " $key" = " y" ] ; then
+		echo "/bin/rm -f $rpmbuild/SOURCES/logalert-$version.tar.bz2"
+		/bin/rm -f $rpmbuild/SOURCES/logalert-$version.tar.bz2
+		echo "/bin/rm -f $rpmbuild/SOURCES/logalert-rpmlintrc"
+		/bin/rm -f $rpmbuild/SOURCES/logalert-rpmlintrc
+	fi
 fi
